service: challenge-back-kalo

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 200
  memory: 2048
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action: '*'
          Resource:
            Fn::Join:
              - ""
              - - "arn:aws:s3:::"
                - "challenge-kalo"
                - "/*"

resources:
  Resources:
    challengeKaloBackDB:
      Type: AWS::RDS::DBInstance
      Properties:
        Engine: mysql
        DBInstanceIdentifier: challenge-kalo-database
        MasterUsername: admin
        MasterUserPassword: rootroot
        AllocatedStorage: 20
        DBInstanceClass: db.t2.micro
        VPCSecurityGroups:
          - sg-0afb89b491edc972a
        AvailabilityZone: us-east-1a
        MultiAZ: false
        PubliclyAccessible: false
        StorageType: gp2
        StorageEncrypted: false
        Tags:
          - Key: Name
            Value: ChallengeKaloDatabase

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  esbuild:
    minify: true
    external:
      - aws-sdk
      - dotenv
      - reflect-metadata
      - typeorm
      - moment
      - moment-timezone
      - bcryptjs
      - jsonwebtoken
      - mysql2
      - middy
      - aws-sdk/client-s3
      - aws-sdk/s3-request-presigner
      - middy/core
      - middy/http-json-body-parser
      - middy/http-multipart-body-parser
      - middy/http-header-normalizer
      - axios
      - lambda-proxy-utils
    watch:
      pattern: [ './index.ts', 'src/**/*.ts' ]
      ignore: [ '.serverless/**/*', '.build' ]
  dotenv:
    path: env.yml
functions:
  - ${file(./src/functions/ping/index.functions.yml)}
  - ${file(./src/functions/auth/index.functions.yml)}
  - ${file(./src/functions/users/index.functions.yml)}
  - ${file(./src/functions/articles/index.functions.yml)}
